// src/Resultado.svelte
<script>
	export let opcoes;

	function calcular(q) {
		var total = 0;
		let reducer = (acc, current) => acc + current;
		if (opcoes) {
			total = opcoes
				.map((v) => {
					return v.quantidade;
				})
				.reduce(reducer);
		}
		return Math.round((q * 100) / total);
	}
</script>

<style>
</style>

<main>
	{#each opcoes as opcao, index (opcao)}
		<p>
			{index+1}
			{opcao.opcao}
			-
			{opcao.quantidade}
			({calcular(opcao.quantidade)}%)
		</p>
	{/each}
</main>

// src/app/resultado.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'resultado',
  template:`<p *ngFor="let op of opcoes; index as idx">
            {{idx}}. {{op.opcao}} - {{op.quantidade}} ({{calcular(op.quantidade)}}%)
          </p>`
})

export class ResultadoComponent {
  @Input() opcoes?: Array<{opcao: string, quantidade: number}>
  calcular(q:number){
    let total = 0;
    let reducer = (acc:number, current:number) => acc + current;
    if(this.opcoes){
      total = this.opcoes.map(v => { return v.quantidade }).reduce(reducer);
    }
    return Math.round(q*100/total);
  }
}
