// src/VotacaoCard.svelte
<script>
	import Cabine from "./Cabine.svelte";
	import Resultado from "./Resultado.svelte";
	export let estado;
	export let texto;
	export let opcoes;

	function onVote(index){
		opcoes[index.detail].quantidade++;
		estado=estado==='open'?'closed':'open';
	}
</script>

<style>
</style>

<main>
	<h1>{texto}</h1>
	{#if estado === 'open'}
		<Cabine on:vote={onVote} {opcoes} />
	{:else}
		<Resultado {opcoes} />
	{/if}
</main>

// src/app/votacaocard.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'votacaocard',
  template: `
  <h1>{{texto}}</h1>
  <div *ngIf="estado === 'open'; else resultado">
    <cabine [opcoes]="opcoes" (voto)="onVoto($event)"></cabine>
  </div>
  <ng-template #resultado>
    <resultado [opcoes]="opcoes"></resultado>
  </ng-template>
  `
})
export class VotacaoCardComponent {
  @Input() opcoes?: Array<{opcao: string, quantidade: number}>
  @Input() estado?: string
  @Input() texto?: string

  onVoto(index: number){
    if(this.opcoes){
      this.opcoes[index-1].quantidade++;
      this.estado = 'closed'
    }
  }

}
