// src/components/Resultado.vue
<template>
  <div>
	<p v-for="(opcao,i) in opcoes" :key="i">
	{{i+1}}. {{opcao.opcao}} - {{opcao.quantidade}} ({{calcular(opcao.quantidade)}}%)
	</p>
  </div>
</template>

<script>
export default {
  name: 'Resultado',
  props: ['opcoes'],
  methods:{
	calcular(q){
		let total = 0;
		let reducer = (acc, current) => acc + current;
		if(this.opcoes){
		total = this.opcoes.map(v => { return v.quantidade }).reduce(reducer);
		}
		return Math.round(q*100/total);
	}
  }

}

</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>

</style>

// src/Resultado.svelte
<script>
	export let opcoes;

	function calcular(q) {
		var total = 0;
		let reducer = (acc, current) => acc + current;
		if (opcoes) {
			total = opcoes
				.map((v) => {
					return v.quantidade;
				})
				.reduce(reducer);
		}
		return Math.round((q * 100) / total);
	}
</script>

<style>
</style>

<main>
	{#each opcoes as opcao, index (opcao)}
		<p>
			{index+1}
			{opcao.opcao}
			-
			{opcao.quantidade}
			({calcular(opcao.quantidade)}%)
		</p>
	{/each}
</main>
